name: Build and Tests

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-latest
    
    permissions:
      contents: write
      discussions: write
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore CADProgramSolution.sln

      - name: Build Solution
        run: |
          msbuild.exe CADProgramSolution.sln /p:platform="x64" /p:configuration="Release"
          
      - uses: vimtor/action-zip@v1
        with:
          files: bin\x64\Release\FindAndReplaceCAD.dll
          dest: release.zip
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.}}
          files: release.zip
          
      
