name: Build and Tests

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-latest
    
    permissions:
      contents: write
      discussions: write
    
    steps:      
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore CADProgramSolution.sln

      - name: Build Solution
        run: |
          msbuild.exe CADProgramSolution.sln /p:platform="x64" /p:configuration="Release"
          
      - name: Find Dir
        run: |
          pwd
          dir
          
      - uses: vimtor/action-zip@latest
        if: ${{ github.event_name == 'push' }}
        with:
          files: bin\x64\Release\FindAndReplaceCAD.dll
          dest: release.zip
          
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
          
      - name: Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          files: release.zip
